# Generated by Django 2.1.1 on 2018-10-04 15:10

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='productos')),
                ('cropping', image_cropping.fields.ImageRatioField('imagen', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('nombre', models.CharField(max_length=180)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
